---
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
output: pdf_document
classoption: landscape
geometry: margin=2cm
---
\pagenumbering{gobble}


```{r setup, include=F}
library(kableExtra)
library(tidyverse)

```

\renewcommand{\arraystretch}{2}
```{r echo=F, warning=FALSE}
kable(points_obtained, format = "latex", 
      #booktabs = T, 
      align = "c") %>%
  column_spec(1:3, width = "6em") %>%
  kable_styling(latex_options = c("repeat_header", "striped"), full_width = F, font_size = 12, stripe_color = "#d5f0c6") %>%
  row_spec(0, align = "c", bold = T, background = "black", color = "white")

```

\renewcommand{\arraystretch}{2}
```{r echo=F, warning=F}
kable(detailed_grade, format = "latex",
      longtable = T, linesep = "",
      booktabs = T,
      align = c("c", "l", "c", "c")) %>%
  
  column_spec(1, width = "5em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3:4, width = "6em") %>%
  kable_styling(latex_options = c("repeat_header", "striped"), full_width = F, font_size = 12, stripe_color = "#d5f0c6") %>%
  row_spec(0, align = "c", bold = T, background = "black", color = "white")


```

\renewcommand{\arraystretch}{2}
```{r echo=F, warning=F}
kable(additional_comments, format = "latex",
      longtable = T, linesep = "",
      booktabs = T,
      
      align = c("l")) %>%
  
  column_spec(1, width = "35em") %>%
  
  kable_styling(latex_options = c("repeat_header", "striped"), full_width = F, font_size = 12, stripe_color = "#d5f0c6") %>%
  row_spec(0, align = "l", bold = T, background = "black", color = "white")


```
